name: 'PEINAKOTHIKI restaurant & catering  '
favicon: null
layout_spectrum: 0.30675617838278413
typography_spectrum: 0.6595143040176481
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#505954'
    - '#353b37'
    - '#babbb5'
    - '#737975'
    - '#05090a'
  brandStrength: 0.8715873812325299
  lightness: 0.8054575198329985
  saturation: 0.5112082650884986
  rhythmicContrast: 0.1567111532203853
purpose: []
